/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopCartIndexRouteImport } from './routes/shop/cart/index'
import { Route as ShopCarsIndexRouteImport } from './routes/shop/cars/index'
import { Route as ShopAccessoriesIndexRouteImport } from './routes/shop/accessories/index'
import { Route as ShopCarsInfoRouteImport } from './routes/shop/cars/info'
import { Route as ShopAccessoriesInfoRouteImport } from './routes/shop/accessories/info'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartIndexRoute = ShopCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCarsIndexRoute = ShopCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccessoriesIndexRoute = ShopAccessoriesIndexRouteImport.update({
  id: '/accessories/',
  path: '/accessories/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCarsInfoRoute = ShopCarsInfoRouteImport.update({
  id: '/cars/info',
  path: '/cars/info',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccessoriesInfoRoute = ShopAccessoriesInfoRouteImport.update({
  id: '/accessories/info',
  path: '/accessories/info',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shop': typeof ShopRouteWithChildren
  '/shop/': typeof ShopIndexRoute
  '/shop/accessories/info': typeof ShopAccessoriesInfoRoute
  '/shop/cars/info': typeof ShopCarsInfoRoute
  '/shop/accessories': typeof ShopAccessoriesIndexRoute
  '/shop/cars': typeof ShopCarsIndexRoute
  '/shop/cart': typeof ShopCartIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shop': typeof ShopIndexRoute
  '/shop/accessories/info': typeof ShopAccessoriesInfoRoute
  '/shop/cars/info': typeof ShopCarsInfoRoute
  '/shop/accessories': typeof ShopAccessoriesIndexRoute
  '/shop/cars': typeof ShopCarsIndexRoute
  '/shop/cart': typeof ShopCartIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shop': typeof ShopRouteWithChildren
  '/shop/': typeof ShopIndexRoute
  '/shop/accessories/info': typeof ShopAccessoriesInfoRoute
  '/shop/cars/info': typeof ShopCarsInfoRoute
  '/shop/accessories/': typeof ShopAccessoriesIndexRoute
  '/shop/cars/': typeof ShopCarsIndexRoute
  '/shop/cart/': typeof ShopCartIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shop'
    | '/shop/'
    | '/shop/accessories/info'
    | '/shop/cars/info'
    | '/shop/accessories'
    | '/shop/cars'
    | '/shop/cart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shop'
    | '/shop/accessories/info'
    | '/shop/cars/info'
    | '/shop/accessories'
    | '/shop/cars'
    | '/shop/cart'
  id:
    | '__root__'
    | '/'
    | '/shop'
    | '/shop/'
    | '/shop/accessories/info'
    | '/shop/cars/info'
    | '/shop/accessories/'
    | '/shop/cars/'
    | '/shop/cart/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart/': {
      id: '/shop/cart/'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cars/': {
      id: '/shop/cars/'
      path: '/cars'
      fullPath: '/shop/cars'
      preLoaderRoute: typeof ShopCarsIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/accessories/': {
      id: '/shop/accessories/'
      path: '/accessories'
      fullPath: '/shop/accessories'
      preLoaderRoute: typeof ShopAccessoriesIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cars/info': {
      id: '/shop/cars/info'
      path: '/cars/info'
      fullPath: '/shop/cars/info'
      preLoaderRoute: typeof ShopCarsInfoRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/accessories/info': {
      id: '/shop/accessories/info'
      path: '/accessories/info'
      fullPath: '/shop/accessories/info'
      preLoaderRoute: typeof ShopAccessoriesInfoRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopIndexRoute: typeof ShopIndexRoute
  ShopAccessoriesInfoRoute: typeof ShopAccessoriesInfoRoute
  ShopCarsInfoRoute: typeof ShopCarsInfoRoute
  ShopAccessoriesIndexRoute: typeof ShopAccessoriesIndexRoute
  ShopCarsIndexRoute: typeof ShopCarsIndexRoute
  ShopCartIndexRoute: typeof ShopCartIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopIndexRoute: ShopIndexRoute,
  ShopAccessoriesInfoRoute: ShopAccessoriesInfoRoute,
  ShopCarsInfoRoute: ShopCarsInfoRoute,
  ShopAccessoriesIndexRoute: ShopAccessoriesIndexRoute,
  ShopCarsIndexRoute: ShopCarsIndexRoute,
  ShopCartIndexRoute: ShopCartIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
