/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileOrdersRouteImport } from './routes/profile/orders'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ShopCheckoutIndexRouteImport } from './routes/shop/checkout/index'
import { Route as ShopCartIndexRouteImport } from './routes/shop/cart/index'
import { Route as ShopCarsIndexRouteImport } from './routes/shop/cars/index'
import { Route as ShopAccessoriesIndexRouteImport } from './routes/shop/accessories/index'
import { Route as ShopCarsInfoRouteImport } from './routes/shop/cars/info'
import { Route as ShopAccessoriesInfoRouteImport } from './routes/shop/accessories/info'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileOrdersRoute = ProfileOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProfileRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ShopCheckoutIndexRoute = ShopCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartIndexRoute = ShopCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCarsIndexRoute = ShopCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccessoriesIndexRoute = ShopAccessoriesIndexRouteImport.update({
  id: '/accessories/',
  path: '/accessories/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCarsInfoRoute = ShopCarsInfoRouteImport.update({
  id: '/cars/info',
  path: '/cars/info',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccessoriesInfoRoute = ShopAccessoriesInfoRouteImport.update({
  id: '/accessories/info',
  path: '/accessories/info',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/accessories/info': typeof ShopAccessoriesInfoRoute
  '/shop/cars/info': typeof ShopCarsInfoRoute
  '/shop/accessories': typeof ShopAccessoriesIndexRoute
  '/shop/cars': typeof ShopCarsIndexRoute
  '/shop/cart': typeof ShopCartIndexRoute
  '/shop/checkout': typeof ShopCheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/shop': typeof ShopIndexRoute
  '/shop/accessories/info': typeof ShopAccessoriesInfoRoute
  '/shop/cars/info': typeof ShopCarsInfoRoute
  '/shop/accessories': typeof ShopAccessoriesIndexRoute
  '/shop/cars': typeof ShopCarsIndexRoute
  '/shop/cart': typeof ShopCartIndexRoute
  '/shop/checkout': typeof ShopCheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/accessories/info': typeof ShopAccessoriesInfoRoute
  '/shop/cars/info': typeof ShopCarsInfoRoute
  '/shop/accessories/': typeof ShopAccessoriesIndexRoute
  '/shop/cars/': typeof ShopCarsIndexRoute
  '/shop/cart/': typeof ShopCartIndexRoute
  '/shop/checkout/': typeof ShopCheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/shop'
    | '/sign-in'
    | '/sign-up'
    | '/profile/orders'
    | '/admin'
    | '/profile/'
    | '/shop/'
    | '/shop/accessories/info'
    | '/shop/cars/info'
    | '/shop/accessories'
    | '/shop/cars'
    | '/shop/cart'
    | '/shop/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/profile/orders'
    | '/admin'
    | '/profile'
    | '/shop'
    | '/shop/accessories/info'
    | '/shop/cars/info'
    | '/shop/accessories'
    | '/shop/cars'
    | '/shop/cart'
    | '/shop/checkout'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/profile'
    | '/shop'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/profile/orders'
    | '/admin/'
    | '/profile/'
    | '/shop/'
    | '/shop/accessories/info'
    | '/shop/cars/info'
    | '/shop/accessories/'
    | '/shop/cars/'
    | '/shop/cart/'
    | '/shop/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/orders': {
      id: '/profile/orders'
      path: '/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof ProfileOrdersRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/shop/checkout/': {
      id: '/shop/checkout/'
      path: '/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart/': {
      id: '/shop/cart/'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cars/': {
      id: '/shop/cars/'
      path: '/cars'
      fullPath: '/shop/cars'
      preLoaderRoute: typeof ShopCarsIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/accessories/': {
      id: '/shop/accessories/'
      path: '/accessories'
      fullPath: '/shop/accessories'
      preLoaderRoute: typeof ShopAccessoriesIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cars/info': {
      id: '/shop/cars/info'
      path: '/cars/info'
      fullPath: '/shop/cars/info'
      preLoaderRoute: typeof ShopCarsInfoRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/accessories/info': {
      id: '/shop/accessories/info'
      path: '/accessories/info'
      fullPath: '/shop/accessories/info'
      preLoaderRoute: typeof ShopAccessoriesInfoRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProfileRouteChildren {
  ProfileOrdersRoute: typeof ProfileOrdersRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileOrdersRoute: ProfileOrdersRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ShopRouteChildren {
  ShopIndexRoute: typeof ShopIndexRoute
  ShopAccessoriesInfoRoute: typeof ShopAccessoriesInfoRoute
  ShopCarsInfoRoute: typeof ShopCarsInfoRoute
  ShopAccessoriesIndexRoute: typeof ShopAccessoriesIndexRoute
  ShopCarsIndexRoute: typeof ShopCarsIndexRoute
  ShopCartIndexRoute: typeof ShopCartIndexRoute
  ShopCheckoutIndexRoute: typeof ShopCheckoutIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopIndexRoute: ShopIndexRoute,
  ShopAccessoriesInfoRoute: ShopAccessoriesInfoRoute,
  ShopCarsInfoRoute: ShopCarsInfoRoute,
  ShopAccessoriesIndexRoute: ShopAccessoriesIndexRoute,
  ShopCarsIndexRoute: ShopCarsIndexRoute,
  ShopCartIndexRoute: ShopCartIndexRoute,
  ShopCheckoutIndexRoute: ShopCheckoutIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
